sonar.projectKey=Devs-Edukativa_moodle-cognus_7f2e4b1c-3a5d-4e8f-9b1a-2c6d5f3a8e2b
sonar.projectName=moodle-cognus
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/tests/**,**/vendor/**,**/cache/**,**/temp/**,**/install/**,**/upgrade/**,**/.git/**,**/mysql-config/**,**/userpix/**,**/pix/**
sonar.scanner.socketTimeout=600
sonar.scanner.responseTimeout=600
sonar.scm.disabled=true
